### ISSUE TITLE
[suggestion] More reasonable default mode bind than `C-q`

### ISSUE THREAD

**Issue by appetrosyan** [ayrat555/cargo-mode#7]
The `C-q` is an important emacs prefix command for converting any bound command to a self-insert command, including stuff that is inserted with control characters/masks. 

It is much better to do something along the lines of `C-c C-a` as a prefix. The `C-c` family is unbound by emacs intentionally, secondly this prefix is easy to type with the left hand on default emacs keybindings, thirdly it is mnemonic: `Hold down ctrl and start spelling out cargo`.

This is just a suggestion, though, feel free to ignore.

**Comment by ayrat555** [comment]
@appetrosyan hey. it's possible to change the prefix as mentioned in the readme:

```listp
To change prefix (default C-q e) use:

 (define-key cargo-minor-mode-map (kbd ...) 'cargo-mode-command-map)
```

**Comment by appetrosyan** [comment]
I understand. That is not what I meant. 

I meant that the `C-q` is not a great default. I often have bindings other than the ones I use as defaults in my packages, because they might override something that the users might have wanted. 

NIT: Also, `define-key` is being deprecated in favour of `keymap-set`, though that will be enforced in emacs 29 and later.

**Comment by ayrat555** [comment]
@appetrosyan both of your suggestions sound reasonable. would it be possible to create a pr?

**Comment by appetrosyan** [comment]
#8 is open. Let me know if you need anything changed.
